const mongoose = require('mongoose');

/**
 * Critical Alert Model
 * Safety alerts with escalation and resolution tracking
 */

const criticalAlertSchema = new mongoose.Schema(
    {
        alertNumber: {
            type: String,
            unique: true,
        },
        // Alert type and source
        alertType: {
            type: String,
            enum: [
                'vital_abnormal',
                'vital_critical',
                'medication_overdue',
                'medication_missed',
                'medication_allergy',
                'medication_interaction',
                'adverse_reaction',
                'patient_deterioration',
                'fall_risk',
                'code_blue',
                'rapid_response',
                'nurse_escalation',
                'task_overdue',
                'critical_lab',
                'other'
            ],
            required: true,
        },
        severity: {
            type: String,
            enum: ['low', 'medium', 'high', 'critical'],
            required: true,
        },
        // Patient context
        patient: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Patient',
            required: true,
        },
        admission: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Admission',
        },
        // Source reference
        source: {
            type: String,
            enum: ['vital_signs', 'medication', 'nursing_task', 'nursing_note', 'lab_result', 'manual'],
            required: true,
        },
        sourceReference: {
            type: mongoose.Schema.Types.ObjectId,
            refPath: 'sourceModel',
        },
        sourceModel: {
            type: String,
            enum: ['VitalSigns', 'MedicationAdministration', 'NursingTask', 'NursingNote', 'LabTest'],
        },
        // Alert details
        title: {
            type: String,
            required: [true, 'Alert title is required'],
        },
        description: {
            type: String,
            required: [true, 'Alert description is required'],
        },
        parameters: {
            type: Map,
            of: mongoose.Schema.Types.Mixed,
        },
        // Generated by
        generatedAt: {
            type: Date,
            default: Date.now,
            required: true,
        },
        generatedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        isAutoGenerated: { type: Boolean, default: true },
        // Alert routing
        notifiedUsers: [
            {
                user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
                role: String,
                notifiedAt: Date,
                notificationMethod: {
                    type: String,
                    enum: ['in_app', 'sms', 'email', 'pager'],
                },
                acknowledged: { type: Boolean, default: false },
                acknowledgedAt: Date,
            },
        ],
        // Primary responder
        primaryResponder: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        assignedDoctor: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        assignedNurse: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        // Status tracking
        status: {
            type: String,
            enum: ['active', 'acknowledged', 'in_progress', 'resolved', 'escalated', 'false_alarm'],
            default: 'active',
        },
        // Acknowledgment
        acknowledgedAt: Date,
        acknowledgedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        acknowledgmentNotes: String,
        // Resolution
        resolvedAt: Date,
        resolvedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        resolutionNotes: String,
        resolutionAction: String,
        // Escalation tracking
        escalations: [
            {
                escalatedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
                escalatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
                escalatedAt: Date,
                reason: String,
                level: Number, // 1, 2, 3...
            },
        ],
        currentEscalationLevel: { type: Number, default: 0 },
        // Response time tracking
        responseTime: Number, // seconds from generation to first acknowledgment
        resolutionTime: Number, // seconds from generation to resolution
        // Related shift
        shift: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'NursingShift',
        },
    },
    {
        timestamps: true,
    }
);

// Indexes
criticalAlertSchema.index({ patient: 1, generatedAt: -1 });
criticalAlertSchema.index({ status: 1 });
criticalAlertSchema.index({ severity: 1 });
criticalAlertSchema.index({ alertType: 1 });
criticalAlertSchema.index({ assignedDoctor: 1 });
criticalAlertSchema.index({ assignedNurse: 1 });

// Auto-generate alert number
criticalAlertSchema.pre('save', async function (next) {
    if (this.isNew && !this.alertNumber) {
        const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');
        const count = await mongoose.model('CriticalAlert').countDocuments();
        this.alertNumber = `ALT${dateStr}${String(count + 1).padStart(5, '0')}`;
    }
    next();
});

// Calculate response time on acknowledgment
criticalAlertSchema.pre('save', function (next) {
    if (this.isModified('acknowledgedAt') && this.acknowledgedAt && this.generatedAt) {
        this.responseTime = Math.floor((this.acknowledgedAt - this.generatedAt) / 1000);
    }
    if (this.isModified('resolvedAt') && this.resolvedAt && this.generatedAt) {
        this.resolutionTime = Math.floor((this.resolvedAt - this.generatedAt) / 1000);
    }
    next();
});

const CriticalAlert = mongoose.model('CriticalAlert', criticalAlertSchema);

module.exports = CriticalAlert;
