const mongoose = require('mongoose');

/**
 * GRN (Goods Receipt Note) Model
 * Represents receipt of goods against purchase orders
 */

const grnItemSchema = new mongoose.Schema({
    item: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'InventoryItem',
        required: true,
    },
    orderedQuantity: {
        type: Number,
        default: 0,
    },
    receivedQuantity: {
        type: Number,
        required: true,
        min: 0,
    },
    acceptedQuantity: {
        type: Number,
        default: 0,
        min: 0,
    },
    rejectedQuantity: {
        type: Number,
        default: 0,
    },
    rejectionReason: {
        type: String,
        trim: true,
    },
    batchNumber: {
        type: String,
        trim: true,
    },
    expiryDate: {
        type: Date,
    },
    manufacturingDate: {
        type: Date,
    },
    rate: {
        type: Number,
        default: 0,
    },
    amount: {
        type: Number,
        default: 0,
    },
    location: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Location',
    },
    qualityCheckPassed: {
        type: Boolean,
        default: true,
    },
    remarks: {
        type: String,
        trim: true,
    },
});

const grnSchema = new mongoose.Schema(
    {
        grnNumber: {
            type: String,
            unique: true,
            // Not required - auto-generated by pre-save hook
        },
        purchaseOrder: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'PurchaseOrder',
            required: [true, 'Purchase Order is required'],
        },
        vendor: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'VendorMaster',
            // Optional - can be derived from PO
        },
        grnDate: {
            type: Date,
            default: Date.now,
        },
        invoiceNumber: {
            type: String,
            trim: true,
        },
        invoiceDate: {
            type: Date,
        },
        invoiceAmount: {
            type: Number,
        },
        challanNumber: {
            type: String,
            trim: true,
        },
        challanDate: {
            type: Date,
        },
        receivingLocation: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Location',
            // Optional - defaults to main store
        },
        items: [grnItemSchema],
        totalReceivedQuantity: {
            type: Number,
            default: 0,
        },
        totalAcceptedQuantity: {
            type: Number,
            default: 0,
        },
        totalAmount: {
            type: Number,
            default: 0,
        },
        discrepancies: {
            type: String,
            trim: true,
        },
        qualityCheckStatus: {
            type: String,
            enum: ['pending', 'passed', 'partial', 'failed'],
            default: 'pending',
        },
        qualityCheckBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        qualityCheckAt: {
            type: Date,
        },
        qualityCheckRemarks: {
            type: String,
            trim: true,
        },
        receivedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
        verifiedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        verifiedAt: {
            type: Date,
        },
        stockUpdated: {
            type: Boolean,
            default: false,
        },
        createdBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
    },
    {
        timestamps: true,
    }
);

// Indexes
grnSchema.index({ grnNumber: 1 });
grnSchema.index({ purchaseOrder: 1 });
grnSchema.index({ vendor: 1 });
grnSchema.index({ grnDate: -1 });
grnSchema.index({ createdAt: -1 });

// Auto-generate GRN number before saving
grnSchema.pre('save', async function (next) {
    if (this.isNew && !this.grnNumber) {
        const today = new Date();
        const dateStr = today.toISOString().slice(0, 10).replace(/-/g, '');
        const count = await mongoose.model('GRN').countDocuments();
        this.grnNumber = `GRN${dateStr}${String(count + 1).padStart(5, '0')}`;
    }
    next();
});

const GRN = mongoose.model('GRN', grnSchema);

module.exports = GRN;
