const mongoose = require('mongoose');
const crypto = require('crypto');

/**
 * OnboardingId Model
 * Represents unique onboarding IDs generated by Admin for staff onboarding
 * 
 * Security Design:
 * - IDs are cryptographically random (not guessable)
 * - Single-use only
 * - Optional expiry
 * - Role pre-assigned and locked
 */

const onboardingIdSchema = new mongoose.Schema(
    {
        // The unique onboarding ID (cryptographically random)
        onboardingCode: {
            type: String,
            required: true,
            unique: true,
            index: true,
        },

        // Pre-assigned role - cannot be changed by user
        role: {
            type: String,
            required: [true, 'Role is required'],
            enum: [
                'doctor',
                'nurse',
                'head_nurse',
                'lab_tech',
                'radiologist',
                'pharmacist',
                'billing',
                'receptionist',
                'inventory_manager',
                'coder',
                'senior_coder',
                'insurance',
                'compliance',
            ],
        },

        // Optional department assignment
        department: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Department',
        },

        // Optional ward assignment (for nurses)
        ward: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Ward',
        },

        // Status of the onboarding ID
        status: {
            type: String,
            enum: ['ACTIVE', 'USED', 'EXPIRED', 'REVOKED'],
            default: 'ACTIVE',
        },

        // Optional expiry date
        expiresAt: {
            type: Date,
        },

        // Who generated this ID
        createdBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },

        // When was it used (if used)
        usedAt: {
            type: Date,
        },

        // Who used this ID (reference to created user)
        usedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },

        // Admin notes
        notes: {
            type: String,
            trim: true,
        },
    },
    {
        timestamps: true,
    }
);

// Indexes for faster queries
onboardingIdSchema.index({ status: 1 });
onboardingIdSchema.index({ createdBy: 1 });
onboardingIdSchema.index({ expiresAt: 1 });

// Static method to generate a cryptographically secure onboarding code
onboardingIdSchema.statics.generateSecureCode = function () {
    // Generate 16 random bytes and convert to hex (32 chars)
    // Format: ONB-XXXX-XXXX-XXXX (more readable)
    const randomBytes = crypto.randomBytes(12).toString('hex').toUpperCase();
    return `ONB-${randomBytes.slice(0, 4)}-${randomBytes.slice(4, 8)}-${randomBytes.slice(8, 12)}`;
};

// Method to check if onboarding ID is still valid
onboardingIdSchema.methods.isValid = function () {
    if (this.status !== 'ACTIVE') {
        return false;
    }

    if (this.expiresAt && new Date() > this.expiresAt) {
        return false;
    }

    return true;
};

// Pre-save hook to auto-expire
onboardingIdSchema.pre('save', function (next) {
    if (this.expiresAt && new Date() > this.expiresAt && this.status === 'ACTIVE') {
        this.status = 'EXPIRED';
    }
    next();
});

const OnboardingId = mongoose.model('OnboardingId', onboardingIdSchema);

module.exports = OnboardingId;
