const mongoose = require('mongoose');
const { PURCHASE_ORDER_STATUS } = require('../config/constants');

/**
 * PurchaseOrder Model
 * Represents purchase orders for non-medicine inventory procurement
 */

const poItemSchema = new mongoose.Schema({
    item: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'InventoryItem',
        required: true,
    },
    description: {
        type: String,
        trim: true,
    },
    quantity: {
        type: Number,
        required: true,
        min: 1,
    },
    receivedQuantity: {
        type: Number,
        default: 0,
    },
    rate: {
        type: Number,
        required: true,
        min: 0,
    },
    discount: {
        type: Number,
        default: 0,
    },
    taxRate: {
        type: Number,
        default: 0,
    },
    taxAmount: {
        type: Number,
        default: 0,
    },
    amount: {
        type: Number,
        required: true,
    },
    remarks: {
        type: String,
        trim: true,
    },
});

const purchaseOrderSchema = new mongoose.Schema(
    {
        poNumber: {
            type: String,
            unique: true,
            // Not required - auto-generated by pre-save hook
        },
        vendor: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'VendorMaster',
            required: [true, 'Vendor is required'],
        },
        purchaseRequisition: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'PurchaseRequisition',
        },
        poDate: {
            type: Date,
            default: Date.now,
        },
        expectedDeliveryDate: {
            type: Date,
        },
        deliveryLocation: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Location',
        },
        items: [poItemSchema],
        subtotal: {
            type: Number,
            default: 0,
        },
        totalDiscount: {
            type: Number,
            default: 0,
        },
        totalTax: {
            type: Number,
            default: 0,
        },
        grandTotal: {
            type: Number,
            default: 0,
        },
        paymentTerms: {
            type: String,
            trim: true,
        },
        deliveryTerms: {
            type: String,
            trim: true,
        },
        notes: {
            type: String,
            trim: true,
        },
        status: {
            type: String,
            enum: Object.values(PURCHASE_ORDER_STATUS),
            default: PURCHASE_ORDER_STATUS.DRAFT,
        },
        approvedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        approvedAt: {
            type: Date,
        },
        cancelledBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        cancelledAt: {
            type: Date,
        },
        cancellationReason: {
            type: String,
            trim: true,
        },
        closedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        closedAt: {
            type: Date,
        },
        auditTrail: [{
            action: { type: String, required: true },
            performedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
            performedAt: { type: Date, default: Date.now },
            details: { type: mongoose.Schema.Types.Mixed },
        }],
        createdBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
    },
    {
        timestamps: true,
    }
);

// Indexes
purchaseOrderSchema.index({ poNumber: 1 });
purchaseOrderSchema.index({ vendor: 1 });
purchaseOrderSchema.index({ status: 1 });
purchaseOrderSchema.index({ poDate: -1 });
purchaseOrderSchema.index({ createdAt: -1 });

// Auto-generate PO number before saving
purchaseOrderSchema.pre('save', async function (next) {
    if (this.isNew && !this.poNumber) {
        const today = new Date();
        const dateStr = today.toISOString().slice(0, 10).replace(/-/g, '');
        const count = await mongoose.model('PurchaseOrder').countDocuments();
        this.poNumber = `PO${dateStr}${String(count + 1).padStart(5, '0')}`;
    }
    next();
});

const PurchaseOrder = mongoose.model('PurchaseOrder', purchaseOrderSchema);

module.exports = PurchaseOrder;
