const mongoose = require('mongoose');
const { STOCK_TRANSFER_STATUS } = require('../config/constants');

/**
 * StockTransfer Model
 * Represents inter-location stock transfers
 */

const transferItemSchema = new mongoose.Schema({
    item: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'InventoryItem',
        required: true,
    },
    quantity: {
        type: Number,
        required: true,
        min: 1,
    },
    receivedQuantity: {
        type: Number,
        default: 0,
    },
    sourceStock: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'InventoryStock',
    },
    batchNumber: {
        type: String,
        trim: true,
    },
    expiryDate: {
        type: Date,
    },
    rate: {
        type: Number,
        default: 0,
    },
    amount: {
        type: Number,
        default: 0,
    },
    remarks: {
        type: String,
        trim: true,
    },
});

const stockTransferSchema = new mongoose.Schema(
    {
        transferNumber: {
            type: String,
            unique: true,
            // Not required - auto-generated by pre-save hook
        },
        sourceLocation: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Location',
            required: [true, 'Source location is required'],
        },
        destinationLocation: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Location',
            required: [true, 'Destination location is required'],
        },
        transferDate: {
            type: Date,
            default: Date.now,
        },
        expectedReceiptDate: {
            type: Date,
        },
        items: [transferItemSchema],
        totalQuantity: {
            type: Number,
            default: 0,
        },
        totalReceivedQuantity: {
            type: Number,
            default: 0,
        },
        totalAmount: {
            type: Number,
            default: 0,
        },
        transferReason: {
            type: String,
            trim: true,
        },
        status: {
            type: String,
            enum: Object.values(STOCK_TRANSFER_STATUS),
            default: STOCK_TRANSFER_STATUS.PENDING,
        },
        requestedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
        approvedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        approvedAt: {
            type: Date,
        },
        dispatchedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        dispatchedAt: {
            type: Date,
        },
        receivedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        receivedAt: {
            type: Date,
        },
        receivingRemarks: {
            type: String,
            trim: true,
        },
        cancelledBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        cancelledAt: {
            type: Date,
        },
        cancellationReason: {
            type: String,
            trim: true,
        },
        sourceStockUpdated: {
            type: Boolean,
            default: false,
        },
        destinationStockUpdated: {
            type: Boolean,
            default: false,
        },
        createdBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
    },
    {
        timestamps: true,
    }
);

// Indexes
stockTransferSchema.index({ transferNumber: 1 });
stockTransferSchema.index({ sourceLocation: 1 });
stockTransferSchema.index({ destinationLocation: 1 });
stockTransferSchema.index({ status: 1 });
stockTransferSchema.index({ transferDate: -1 });

// Auto-generate transfer number before saving
stockTransferSchema.pre('save', async function (next) {
    if (this.isNew && !this.transferNumber) {
        const today = new Date();
        const dateStr = today.toISOString().slice(0, 10).replace(/-/g, '');
        const count = await mongoose.model('StockTransfer').countDocuments();
        this.transferNumber = `TRF${dateStr}${String(count + 1).padStart(5, '0')}`;
    }
    next();
});

const StockTransfer = mongoose.model('StockTransfer', stockTransferSchema);

module.exports = StockTransfer;
