const mongoose = require('mongoose');
const { STOCK_ISSUE_STATUS } = require('../config/constants');

/**
 * StockIssue Model
 * Represents stock issue requests to departments or locations
 */

const issueItemSchema = new mongoose.Schema({
    item: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'InventoryItem',
        required: true,
    },
    requestedQuantity: {
        type: Number,
        required: true,
        min: 1,
    },
    approvedQuantity: {
        type: Number,
        default: 0,
    },
    issuedQuantity: {
        type: Number,
        default: 0,
    },
    stock: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'InventoryStock',
    },
    batchNumber: {
        type: String,
        trim: true,
    },
    expiryDate: {
        type: Date,
    },
    rate: {
        type: Number,
        default: 0,
    },
    amount: {
        type: Number,
        default: 0,
    },
    remarks: {
        type: String,
        trim: true,
    },
});

const stockIssueSchema = new mongoose.Schema(
    {
        issueNumber: {
            type: String,
            unique: true,
            // Not required - auto-generated by pre-save hook
        },
        requestingDepartment: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Department',
            // Optional - can use requestingLocation instead
        },
        requestingLocation: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Location',
        },
        issuingLocation: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Location',
            // Optional - defaults to main store if not provided
        },
        requestDate: {
            type: Date,
            default: Date.now,
        },
        requiredByDate: {
            type: Date,
        },
        priority: {
            type: String,
            enum: ['low', 'normal', 'high', 'urgent'],
            default: 'normal',
        },
        items: [issueItemSchema],
        totalRequestedQuantity: {
            type: Number,
            default: 0,
        },
        totalIssuedQuantity: {
            type: Number,
            default: 0,
        },
        totalAmount: {
            type: Number,
            default: 0,
        },
        purpose: {
            type: String,
            trim: true,
        },
        status: {
            type: String,
            enum: Object.values(STOCK_ISSUE_STATUS),
            default: STOCK_ISSUE_STATUS.PENDING,
        },
        requestedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
        approvedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        approvedAt: {
            type: Date,
        },
        rejectedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        rejectedAt: {
            type: Date,
        },
        rejectionReason: {
            type: String,
            trim: true,
        },
        issuedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        issuedAt: {
            type: Date,
        },
        receivedBy: {
            name: { type: String, trim: true },
            signature: { type: String },
            receivedAt: { type: Date },
        },
        createdBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
    },
    {
        timestamps: true,
    }
);

// Indexes
stockIssueSchema.index({ issueNumber: 1 });
stockIssueSchema.index({ requestingDepartment: 1 });
stockIssueSchema.index({ issuingLocation: 1 });
stockIssueSchema.index({ status: 1 });
stockIssueSchema.index({ requestDate: -1 });

// Auto-generate issue number before saving
stockIssueSchema.pre('save', async function (next) {
    if (this.isNew && !this.issueNumber) {
        const today = new Date();
        const dateStr = today.toISOString().slice(0, 10).replace(/-/g, '');
        const count = await mongoose.model('StockIssue').countDocuments();
        this.issueNumber = `ISS${dateStr}${String(count + 1).padStart(5, '0')}`;
    }
    next();
});

const StockIssue = mongoose.model('StockIssue', stockIssueSchema);

module.exports = StockIssue;
